# Project: WPaperMinecraft
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = WPaperMinecraft_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/devcpp_setup/devcpp_setup/MinGW64/lib32" -L"D:/devcpp_setup/devcpp_setup/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"D:/devcpp_setup/devcpp_setup/MinGW64/include" -I"D:/devcpp_setup/devcpp_setup/MinGW64/x86_64-w64-mingw32/include" -I"D:/devcpp_setup/devcpp_setup/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/devcpp_setup/devcpp_setup/MinGW64/include" -I"D:/devcpp_setup/devcpp_setup/MinGW64/x86_64-w64-mingw32/include" -I"D:/devcpp_setup/devcpp_setup/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/devcpp_setup/devcpp_setup/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = WPaperMinecraft.exe
CXXFLAGS = $(CXXINCS) -ansi -m32 -g3 -std=c++11 -DMYCOM
CFLAGS   = $(INCS) -ansi -m32 -g3 -std=c++11 -DMYCOM
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

WPaperMinecraft_private.res: WPaperMinecraft_private.rc resource.rc
	$(WINDRES) -i WPaperMinecraft_private.rc -F pe-i386 --input-format=rc -o WPaperMinecraft_private.res -O coff 

